# ----------------
# Files and folders
# ----------------

input_dir: "/home/joca00004/data/ecoli_real"
output_dir: "/home/joca00004/out"
temp_dir: "/home/joca00004/temp"
gbff_file: "/home/joca00004/data/db/Escherichia_coli.gbff"
fasta_file: "/home/joca00004/data/reference/Escherichia_coli.fasta"
env_dir: ""

# Each rule supplies its own image name and version to this format string.
container_format: "docker://docker.io/cambouu/alpar-smk-{0}"

# ----------------
# Parameters
# ----------------

genus: "ecoli"
gpa_method: "cd-hit"
mock: False
