package:
  name: "alpar"
  version: '1.3.2'

source:
  path: ..

build:
  noarch: python
  entry_points:
    - alpar = sr_amr.amr:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.12
    - setuptools
    - pip
  run:
    - python >=3.12
    - pandas
    - numpy
    - psutil
    - biopython
    - joblib
    - tqdm

about:
  home: https://github.com/kalininalab/ALPAR
  license: MIT
  license_file: LICENSE
  summary: Automated Learning Pipeline for Antimicrobial Resistance
