package:
  name: "alpar"
  version: '1.1.2'

source:
  path: ..

build:
  entry_points:
    - alpar = sr_amr.amr:main
  script: python setup.py install

requirements:
  build:
    - python >=3.9,<3.12
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >=3.9,<3.12
    - snippy
    - panaroo
    - seaborn
    - datasail>=1.0.0
    - ete3
    - python
    - swig
    - grakel
    - mashtree
    - iqtree
    - pyseer
    - xgboost
    - scip==8.0.4

about:
  home: https://github.com/kalininalab/ALPAR
  license: MIT
  license_file: LICENSE
  summary: Automated Learning Pipeline for Antimicrobial Resistance
