package:
  name: "sr-amr"
  version: '0.1.1'

source:
  path: ..

build:
  entry_points:
    - sr-amr = scripts.sr-amr:main
  script: python setup.py install

requirements:
  build:
    - python==3.9
    - setuptools
    - setuptools_scm
    - pip
  run:
    - snippy
    - prokka
    - panaroo
    - panacota
    - seaborn
    - matplotlib
    - datasail>=0.2.2
    - ete3
    - tqdm
    - python==3.9
    - pandas
    - scikit-learn

about:
  home: https://github.com/kalininalab/SR-AMR
  license: MIT
  license_file: LICENSE
  summary: SR-AMR is a tool for generating binary matrices suitable for machine learning from genomic fasta data
