package:
  name: "sr-amr"
  version: '0.3.1'

source:
  path: ..

build:
  entry_points:
    - sr-amr = scripts.sr_amr:main
  script: python setup.py install

requirements:
  build:
    - python==3.9
    - setuptools
    - setuptools_scm
    - pip
  run:
    - snippy
    - panaroo
    - seaborn
    - datasail>=1.0.0
    - ete3
    - python==3.9
    - auto-sklearn
    - swig
    - panacota
    - grakel

about:
  home: https://github.com/kalininalab/SR-AMR
  license: MIT
  license_file: LICENSE
  summary: SR-AMR is a tool for generating binary matrices suitable for machine learning from genomic fasta data
