package:
  name: "sr-amr"
  version: '0.4.0'

source:
  path: ..

build:
  entry_points:
    - sr-amr = sr_amr.amr:main
  script: python setup.py install

requirements:
  build:
    - python>=3.9,<3.10
    - setuptools
    - setuptools_scm
    - pip
  run:
    - snippy
    - panaroo
    - seaborn
    - datasail>=1.0.0
    - ete3
    - python>=3.9,<3.10
    - auto-sklearn
    - swig
    - grakel
    - mashtree
    - iqtree
    - pyseer

about:
  home: https://github.com/kalininalab/SR-AMR
  license: MIT
  license_file: LICENSE
  summary: SR-AMR is a tool for generating binary matrices suitable for machine learning from genomic fasta data
