package:
  name: "alpar"
  version: '0.8.0'

source:
  path: ..

build:
  entry_points:
    - alpar = sr_amr.amr:main
  script: python setup.py install

requirements:
  build:
    - python>=3.9,<3.10
    - setuptools
    - setuptools_scm
    - pip
  run:
    - snippy
    - panaroo
    - seaborn
    - datasail>=1.0.0
    - ete3
    - python>=3.9,<3.10
    - auto-sklearn
    - swig
    - grakel
    - mashtree
    - iqtree
    - pyseer
    - xgboost

about:
  home: https://github.com/kalininalab/ALPAR
  license: MIT
  license_file: LICENSE
  summary: Automated Learning Pipeline for Antimicrobial Resistance
