name: alpar
channels:
  - conda-forge
  - bioconda
  - kalininalab
  - etetoolkit
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - scikit-learn>=1.0
  - seaborn
  - matplotlib
  - xgboost
  - joblib
  - snippy
  - prokka
  - bakta
  - panaroo
  - pyseer
  - mashtree
  - panacota
  - cd-hit
  - blast
  - pip:
    - datasail
